### ISSUE TITLE
Will rdf-dot support RDF* ?

### ISSUE THREAD

**Issue by joylix** [vcharpenay/rdf-dot#1]
The W3C's  RDF* specification is  nearing completion， It is supported by a growing number of graph databases, 

The latest spec version is at:  https://w3c.github.io/rdf-star/cg-spec/editors_draft.html
 what is RDF*:       https://enterprise-knowledge.com/rdf-what-is-it-and-why-do-i-need-it/ 
It would be great if we could use rdf-dot to handle RDF* file.

**Comment by vcharpenay** [comment]
DOT is not the most suitable language for recursive graphs, as far as I know.

By the way, this project is not going to be edited further, I'll archive it.
